### ISSUE TITLE
dataset.csv sumas parciales

### ISSUE THREAD

**Issue by afreisinger** [edvm/coronavirus-argentina#6]
hay sumas parciales incluidas en el dataset.csv donde country_or_region='' ? es correcto ?

**Comment by edvm** [comment]
@afreisinger cuando `country_or_region=''` los valores corresponden al total de casos acumulados al dia de la fecha dada en esa row.
Tambien te comento que el dataset en *.json trae muchisima mas informacion que el csv (de hecho el *.csv lo generamos desde el *.json). Podes ver la referencia de la info que trae el dataset en json en: https://edvm.github.io/coronavirus-argentina/ (abajo de todo).
Saludos!

**Comment by afreisinger** [comment]
@edvm excelente trabajo.
Saludos!
