### ISSUE TITLE
Actualizaciones

### ISSUE THREAD

**Issue by afreisinger** [edvm/coronavirus-argentina#7]
Nos quedamos sin actualizaciones desde el 19/4 ?

**Comment by edvm** [comment]
Buenas @afreisinger , si! Decidimos parar de actualizar esta DB porque hay un proyecto que viene andando muy bien (y tienen muchas mas herramientas) que se llama Arcovid 19.
Podes pegarle un ojo por aca:
https://ivco19.github.io/

Gracias por cargar este issue, ahora actualizo el README mencionando esto mismo.
Saludos!

**Comment by datoslibres** [comment]
Hola!  PERDON!!   si, hubo un vacio, estuve con otro proyecto pero hoy me
puse las pilas nuevamente.  Recien veo el correo, pero mejor tarde que
nunca!! Gracias, hoy comparti tu enlace en el blog y en el foro. Seguimos
en contacto.
